import datasets
import AdaBoost
import Bagging

if __name__ == '__main__':
    wine_dataset = datasets.load_wine_dataset()
    glass_dataset = datasets.load_glass_dataset()
    brestTissue_dataset = datasets.load_breastTissue_dataset()
    diabetes_dataset = datasets.load_diabetes_dataset()
    sonar_dataset = datasets.load_sonar_dataset()
    ionosphere_dataset = datasets.load_ionosphere_dataset()

    t_count = int(input('Enter T : '))


    print(f'With no noise T = {t_count}')
    print('Wine ',end= ' : ')
    Bagging.bagging_test_model(wine_dataset,t_count,0)
    print('Glass ',end=': ')
    Bagging.bagging_test_model(glass_dataset,t_count,0)
    print('Breast Tissue ',end=': ')
    Bagging.bagging_test_model(brestTissue_dataset,t_count,0)
    AdaBoost.adaboost_test_model(brestTissue_dataset,2,t_count,0)
    print('Diabetes ',end=': ')
    Bagging.bagging_test_model(diabetes_dataset,t_count,0)
    AdaBoost.adaboost_test_model(diabetes_dataset,2,t_count,0)
    print('Sonar ',end=': ')
    Bagging.bagging_test_model(sonar_dataset,t_count,0)
    AdaBoost.adaboost_test_model(sonar_dataset,2,t_count,0)
    print('Ionosphere ',end=': ')
    Bagging.bagging_test_model(ionosphere_dataset,t_count,0)
    AdaBoost.adaboost_test_model(ionosphere_dataset,2,t_count,0)

    print(f'With 10% Noise T = {t_count}')
    print('Wine ',end= ' : ')
    Bagging.bagging_test_model(wine_dataset,t_count,0.1)
    print('Glass ',end=': ')
    Bagging.bagging_test_model(glass_dataset,t_count,0.1)
    print('Breast Tissue ',end=': ')
    Bagging.bagging_test_model(brestTissue_dataset,t_count,0.1)
    AdaBoost.adaboost_test_model(brestTissue_dataset,2,t_count,0.1)
    print('Diabetes ',end=': ')
    Bagging.bagging_test_model(diabetes_dataset,t_count,0.1)
    AdaBoost.adaboost_test_model(diabetes_dataset,2,t_count,0.1)
    print('Sonar ',end=': ')
    Bagging.bagging_test_model(sonar_dataset,t_count,0.1)
    AdaBoost.adaboost_test_model(sonar_dataset,2,t_count,0.1)
    print('Ionosphere ',end=': ')
    Bagging.bagging_test_model(ionosphere_dataset,t_count,0.1)
    AdaBoost.adaboost_test_model(ionosphere_dataset,2,t_count,0.1)

    print(f'With 20% Noise T = {t_count}')
    print('Wine ',end= ' : ')
    Bagging.bagging_test_model(wine_dataset,t_count,0.2)
    print('Glass ',end=': ')
    Bagging.bagging_test_model(glass_dataset,t_count,0.2)
    print('Breast Tissue ',end=': ')
    Bagging.bagging_test_model(brestTissue_dataset,t_count,0.2)
    AdaBoost.adaboost_test_model(brestTissue_dataset,2,t_count,0.2)
    print('Diabetes ',end=': ')
    Bagging.bagging_test_model(diabetes_dataset,t_count,0.2)
    AdaBoost.adaboost_test_model(diabetes_dataset,2,t_count,0.2)
    print('Sonar ',end=': ')
    Bagging.bagging_test_model(sonar_dataset,t_count,0.2)
    AdaBoost.adaboost_test_model(sonar_dataset,2,t_count,0.2)
    print('Ionosphere ',end=': ')
    Bagging.bagging_test_model(ionosphere_dataset,t_count,0.2)
    AdaBoost.adaboost_test_model(ionosphere_dataset,2,t_count,0.2)

    print(f'With 30% Noise T = {t_count}')
    print('Wine ',end= ' : ')
    Bagging.bagging_test_model(wine_dataset,t_count,0.3)
    print('Glass ',end=': ')
    Bagging.bagging_test_model(glass_dataset,t_count,0.3)
    print('Breast Tissue ',end=': ')
    Bagging.bagging_test_model(brestTissue_dataset,t_count,0.3)
    AdaBoost.adaboost_test_model(brestTissue_dataset,2,t_count,0.3)
    print('Diabetes ',end=': ')
    Bagging.bagging_test_model(diabetes_dataset,t_count,0.3)
    AdaBoost.adaboost_test_model(diabetes_dataset,2,t_count,0.3)
    print('Sonar ',end=': ')
    Bagging.bagging_test_model(sonar_dataset,t_count,0.3)
    AdaBoost.adaboost_test_model(sonar_dataset,2,t_count,0.3)
    print('Ionosphere ',end=': ')
    Bagging.bagging_test_model(ionosphere_dataset,t_count,0.3)
    AdaBoost.adaboost_test_model(ionosphere_dataset,2,t_count,0.3)
